import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, MapPin, Truck, Calendar, ShoppingBag } from 'lucide-react';
import axios from 'axios';

const STATUS_STEPS = [
  { key: 'placed', label: 'Order Placed', desc: 'Order received and payment confirmed.' },
  { key: 'packed', label: 'Packed by Seller', desc: 'Items packed and ready for dispatch.' },
  { key: 'in_transit', label: 'In Transit', desc: 'Picked up and shipping through courier.' },
  { key: 'out_for_delivery', label: 'Out for Delivery', desc: 'Courier agent delivering to address.' },
  { key: 'delivered', label: 'Delivered', desc: 'Successfully delivered to customer.' }
];

export default function TrackOrder() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchOrder = async () => {
      try {
        const token = localStorage.getItem('ps_token');
        const res = await axios.get(`http://localhost:5000/api/orders/${id}/tracking`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (res.data.success) {
          setOrder(res.data.tracking);
        }
      } catch (err) {
        console.error('Fetch track order error:', err);
        // Mock fallback if offline/backend fails
        setOrder({
          orderId: id,
          status: 'in_transit',
          grossAmount: 430,
          paymentMode: 'Prepaid',
          courierPartner: 'Delhivery',
          awbNumber: 'DLV99128301',
          deliveryAddress: { line1: '123 Sweet Cow Colony', city: 'Pune', state: 'Maharashtra', pincode: '411001' },
          timeline: [
            { status: 'placed', timestamp: new Date(Date.now() - 24*3600000), note: 'Order placed by customer' },
            { status: 'packed', timestamp: new Date(Date.now() - 18*3600000), note: 'Packed by Gau Kripa Dairy' },
            { status: 'in_transit', timestamp: new Date(Date.now() - 6*3600000), note: 'AWB DLV99128301 generated by Delhivery' }
          ]
        });
      } finally {
        setLoading(false);
      }
    };

    fetchOrder();
  }, [id]);

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <div className="tab-pill active">Loading tracking info...</div>
      </div>
    );
  }

  if (!order) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh', gap: 16 }}>
        <h2>Order Not Found</h2>
        <button onClick={() => navigate('/my-orders')} className="btn btn-primary">Back to Orders</button>
      </div>
    );
  }

  // Determine current active step index in standard steps list
  const currentStatusIndex = STATUS_STEPS.findIndex(step => step.key === order.status);

  return (
    <div style={{ minHeight: '100vh', background: 'var(--yellow-50)', paddingBottom: 48 }}>
      {/* Header */}
      <header style={{ background: '#fff', borderBottom: '1px solid var(--gray-200)' }}>
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '12px 24px', display: 'flex', alignItems: 'center' }}>
          <button className="btn btn-ghost" onClick={() => navigate('/my-orders')} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <ArrowLeft size={16} /> Back to History
          </button>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 800, margin: '32px auto 0', padding: '0 24px' }}>
        
        {/* Order Info Card */}
        <div className="card" style={{ background: '#fff', padding: 24, border: '1px solid var(--gray-200)', borderRadius: 12, marginBottom: 24 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
            <div>
              <h3 style={{ margin: 0, fontWeight: 800, fontSize: 18, color: 'var(--gray-900)' }}>
                Tracking Order #{order.orderId}
              </h3>
              <span className={`status-badge ${order.status}`} style={{ marginTop: 8 }}>
                {order.status}
              </span>
            </div>
            
            <div style={{ textAlign: 'right' }}>
              <span style={{ fontSize: 12, color: 'var(--gray-500)', display: 'block' }}>Payment Method</span>
              <strong style={{ fontSize: 13, color: 'var(--gray-800)' }}>{order.paymentMode}</strong>
            </div>
          </div>

          {order.awbNumber && (
            <div style={{ marginTop: 16, background: 'var(--gray-50)', border: '1px solid var(--gray-200)', borderRadius: 8, padding: 12, display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
              <span>Courier: <strong>{order.courierPartner || 'Easy Ship Partner'}</strong></span>
              <span>AWB Number: <strong className="mono">{order.awbNumber}</strong></span>
            </div>
          )}
        </div>

        {/* Timeline Layout */}
        <div style={{ display: 'grid', gridTemplateColumns: '1.8fr 1.2fr', gap: 24, alignItems: 'flex-start' }}>
          
          {/* Vertical Timeline Card */}
          <div className="card" style={{ background: '#fff', padding: 32, border: '1px solid var(--gray-200)', borderRadius: 12 }}>
            <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 24 }}>Delivery Progress</h3>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
              {STATUS_STEPS.map((step, index) => {
                const isPassed = index <= currentStatusIndex;
                const isCurrent = index === currentStatusIndex;
                
                // Try to find matching timestamp in order.timeline
                const timelineMatch = order.timeline?.find(t => t.status === step.key);

                return (
                  <div key={step.key} style={{ display: 'flex', gap: 16, position: 'relative', paddingBottom: index === STATUS_STEPS.length - 1 ? 0 : 28 }}>
                    {/* Vertical connecting line */}
                    {index !== STATUS_STEPS.length - 1 && (
                      <div 
                        style={{ 
                          position: 'absolute', 
                          left: 11, 
                          top: 24, 
                          bottom: 0, 
                          width: 2, 
                          background: index < currentStatusIndex ? 'var(--tile-green-dark)' : 'var(--gray-200)' 
                        }} 
                      />
                    )}

                    {/* Dot */}
                    <div 
                      style={{ 
                        width: 24, 
                        height: 24, 
                        borderRadius: '50%', 
                        background: isCurrent ? 'var(--yellow-500)' : isPassed ? 'var(--tile-green-dark)' : 'var(--gray-200)',
                        border: isCurrent ? '4px solid var(--yellow-200)' : 'none',
                        zIndex: 10,
                        flexShrink: 0
                      }} 
                    />

                    {/* Content */}
                    <div style={{ flex: 1, marginTop: 2 }}>
                      <h4 style={{ 
                        fontSize: 14, 
                        fontWeight: isCurrent ? 700 : 600, 
                        color: isPassed ? 'var(--gray-900)' : 'var(--gray-400)' 
                      }}>
                        {step.label}
                      </h4>
                      <p style={{ 
                        fontSize: 11, 
                        color: isPassed ? 'var(--gray-600)' : 'var(--gray-400)',
                        marginTop: 4 
                      }}>
                        {timelineMatch ? timelineMatch.note : step.desc}
                      </p>
                      
                      {timelineMatch && (
                        <span style={{ fontSize: 10, color: 'var(--gray-400)', display: 'block', marginTop: 4 }}>
                          {new Date(timelineMatch.timestamp).toLocaleString()}
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Shipping Address Recap Card */}
          <div className="card" style={{ background: '#fff', padding: 24, border: '1px solid var(--gray-200)', borderRadius: 12 }}>
            <h3 style={{ fontWeight: 700, fontSize: 15, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 6 }}>
              <MapPin size={16} /> Delivery Address
            </h3>
            
            <div style={{ fontSize: 13, color: 'var(--gray-700)', lineHeight: 1.5 }}>
              <strong>{order.buyerName}</strong>
              <div style={{ marginTop: 6 }}>{order.deliveryAddress?.line1}</div>
              <div>{order.deliveryAddress?.city}, {order.deliveryAddress?.state}</div>
              <div>Pincode: {order.deliveryAddress?.pincode}</div>
              <div style={{ marginTop: 8, color: 'var(--gray-500)', fontSize: 12 }}>Phone: {order.buyerPhone}</div>
            </div>
          </div>

        </div>

      </main>
    </div>
  );
}
